#!/usr/bin/env bash
# Merges every tool report in .quality/ into .quality/report.json — failures only, normalized as
# {tool, stage, rule, severity, file, line, message}. Exit 0 only when there are no failures.
# Generated by the quality-gate skill; called by run.sh.
set -uo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

OUT=".quality"
STAGES="format,static,security,deadcode,complexity,duplication,tests"
SCOPE="[]"
CYCLOMATIC_MAX=10
COGNITIVE_MAX=15
DUPLICATION_MAX=3

while [[ $# -gt 0 ]]; do
  case "$1" in
    --stages) STAGES="$2"; shift 2 ;;
    --scope) SCOPE="$2"; shift 2 ;;
    --cyclomatic-max) CYCLOMATIC_MAX="$2"; shift 2 ;;
    --cognitive-max) COGNITIVE_MAX="$2"; shift 2 ;;
    --duplication-max) DUPLICATION_MAX="$2"; shift 2 ;;
    *) echo "usage: aggregate.sh [--stages a,b] [--scope JSON] [--cyclomatic-max N] [--cognitive-max N] [--duplication-max N]" >&2; exit 2 ;;
  esac
done

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# Tool -> stage (tools whose rules span stages are routed per rule below).
STAGE_OF='{
  "gofmt":"format","ruff-format":"format","biome-format":"format","php-cs-fixer":"format",
  "staticcheck":"static","ruff-check":"static","mypy":"static","biome-lint":"static","phan":"static","phpstan":"static",
  "gitleaks":"security","semgrep":"security","gosec":"security","bandit":"security","biome-security":"security",
  "deadcode":"deadcode","staticcheck-u1000":"deadcode","vulture":"deadcode","knip":"deadcode","phpmd-unused":"deadcode",
  "gocyclo":"complexity","gocognit":"complexity","radon":"complexity","complexipy":"complexity",
  "oxlint":"complexity","phpmd-complexity":"complexity",
  "jscpd":"duplication"
}'

valid_json() { [[ -s "$1" ]] && jq -e . "$1" >/dev/null 2>&1; }

tool_error() {
  local p_tool="$1" p_msg="$2"
  jq -cn --arg tool "$p_tool" --argjson map "$STAGE_OF" --arg message "$p_msg" \
    '{tool:$tool, stage:($map[$tool] // "tests"), rule:"tool-error", severity:"error", file:"", line:0, message:$message}' >> "$TMP"
}

log_tail() { tail -n 10 "${OUT}/$1.log" 2>/dev/null | tr '\n' ' ' | cut -c1-1000; }

shopt -s nullglob

# SARIF: keep error/warning results (SARIF's default level is warning).
for p_file in "${OUT}"/*.sarif; do
  p_tool="$(basename "$p_file" .sarif)"
  valid_json "$p_file" || continue
  jq -c --arg tool "$p_tool" --argjson map "$STAGE_OF" '
    .runs[]? | (.tool.driver.name // $tool) as $drv | .results[]?
    | select((.level // "warning") | IN("error", "warning"))
    | {tool:$tool, stage:$map[$tool], rule:(.ruleId // $drv), severity:(.level // "warning"),
       file:(.locations[0].physicalLocation.artifactLocation.uri // ""),
       line:(.locations[0].physicalLocation.region.startLine // 0),
       message:(.message.text // .message.markdown // "")}' "$p_file" >> "$TMP"
done

# Lines already normalized by run.sh.
for p_file in "${OUT}"/*.norm.jsonl; do
  cat "$p_file" >> "$TMP"
done

# mypy: JSON Lines.
if [[ -s "${OUT}/mypy.jsonl" ]]; then
  jq -c 'select(.severity == "error")
    | {tool:"mypy", stage:"static", rule:(.code // "mypy"), severity:"error", file:.file, line:(.line // 0),
       message:(.message + (if .hint then " (" + .hint + ")" else "" end))}' "${OUT}/mypy.jsonl" >> "$TMP" 2>/dev/null
fi

# PHP-CS-Fixer (dry run).
if valid_json "${OUT}/php-cs-fixer.json"; then
  jq -c '.files[]? | {tool:"php-cs-fixer", stage:"format", rule:"php-cs-fixer", severity:"error", file:.name, line:0,
    message:("file is not formatted" + ((.appliedFixers // []) | if length > 0 then ": " + join(", ") else "" end))}' "${OUT}/php-cs-fixer.json" >> "$TMP"
fi

# PHPStan: unused-code rules -> deadcode, cognitive complexity -> complexity.
if valid_json "${OUT}/phpstan.json"; then
  jq -c '
    (.files // {} | to_entries[] | .key as $f | .value.messages[]
      | (.identifier // "phpstan") as $id
      | {tool:"phpstan",
         stage:(if ($id | test("unused"; "i")) then "deadcode"
                elif ($id | test("complexity"; "i")) or (.message | test("^Cognitive complexity"; "i")) then "complexity"
                else "static" end),
         rule:$id, severity:"error", file:$f, line:(.line // 0), message:.message}),
    (.errors[]? | {tool:"phpstan", stage:"static", rule:"phpstan-error", severity:"error", file:"", line:0, message:.})
  ' "${OUT}/phpstan.json" >> "$TMP"
fi

# Phan: normal (5) and critical (10) severities.
if valid_json "${OUT}/phan.json"; then
  jq -c '.[]? | select((.severity // 0) >= 5)
    | {tool:"phan", stage:"static", rule:(.check_name // "phan"),
       severity:(if .severity >= 10 then "error" else "warning" end),
       file:(.location.path // ""), line:(.location.lines.begin // 0), message:(.description // "")}' \
    "${OUT}/phan.json" >> "$TMP"
fi

# Knip: every issue kind listed per file, plus unused files.
if valid_json "${OUT}/knip.json"; then
  jq -c '
    (.files[]? | {tool:"knip", stage:"deadcode", rule:"files", severity:"error", file:., line:0, message:"unused file"}),
    (.issues[]? | .file as $f | to_entries[] | select(.value | type == "array") | .key as $kind | .value[]
      | {tool:"knip", stage:"deadcode", rule:$kind, severity:"error", file:$f, line:(.line // 0),
         message:("unused " + $kind + ": " + (.name // (. | tostring)))}),
    (.issues[]? | .file as $f | to_entries[] | select(.value | type == "object") | .key as $kind | .value | to_entries[] | .value
      | select(type == "object")
      | {tool:"knip", stage:"deadcode", rule:$kind, severity:"error", file:$f, line:(.line // 0),
         message:("unused " + $kind + ": " + (.name // (. | tostring)))})
  ' "${OUT}/knip.json" >> "$TMP"
fi

# Radon: cyclomatic complexity above threshold.
if valid_json "${OUT}/radon.json"; then
  jq -c --argjson max "$CYCLOMATIC_MAX" '
    to_entries[] | .key as $f | .value | arrays | .[]
    | (., (.methods[]? // empty))
    | select(.complexity > $max)
    | {tool:"radon", stage:"complexity", rule:"cyclomatic", severity:"error", file:$f, line:(.lineno // 0),
       message:("cyclomatic complexity of " + ((.classname // "" | if . == "" then "" else . + "." end) + .name)
                + " is " + (.complexity | tostring) + " (max " + ($max | tostring) + ")")}
  ' "${OUT}/radon.json" | sort -u >> "$TMP"
fi

# jscpd: fail only when total duplication exceeds the threshold.
if valid_json "${OUT}/jscpd/jscpd-report.json"; then
  jq -c --argjson max "$DUPLICATION_MAX" '
    (.statistics.total.percentage // 0) as $pct
    | select($pct > $max) | .duplicates[]?
    | {tool:"jscpd", stage:"duplication", rule:("duplication-" + (.format // "code")), severity:"error",
       file:.firstFile.name, line:(.firstFile.start // 0),
       message:("duplicated " + (.lines | tostring) + " lines with " + .secondFile.name + ":" + (.secondFile.start | tostring)
                + " (total " + ($pct | tostring) + "% > " + ($max | tostring) + "%)")}
  ' "${OUT}/jscpd/jscpd-report.json" >> "$TMP"
fi

# A tool that exited non-zero without a usable report is a broken audit, not a pass.
for p_exit in "${OUT}"/*.exit; do
  p_tool="$(basename "$p_exit" .exit)"
  [[ "$(cat "$p_exit")" == "0" ]] && continue
  p_ok=0
  for p_report in "${OUT}/${p_tool}.sarif" "${OUT}/${p_tool}.json" "${OUT}/${p_tool}.jsonl" "${OUT}/${p_tool}/jscpd-report.json"; do
    if [[ "$p_report" == *.jsonl ]]; then
      [[ -s "$p_report" ]] && head -1 "$p_report" | jq -e . >/dev/null 2>&1 && p_ok=1
    else
      valid_json "$p_report" && p_ok=1
    fi
  done
  [[ $p_ok -eq 1 ]] || tool_error "$p_tool" "exit $(cat "$p_exit") without a report: $(log_tail "$p_tool")"
done

jq -s --arg root "$ROOT" --arg stages "$STAGES" --argjson scope "$SCOPE" '
  ["format","static","security","deadcode","complexity","duplication","tests"] as $order
  | ($stages | split(",")) as $wanted
  | ($scope | map(sub("^\\./"; "") | sub("/$"; ""))) as $scope
  | map(.file = ((.file // "") | sub("^file://"; "") | sub("^" + $root + "/"; "") | sub("^\\./"; "")))
  | map(select(.stage as $s | $wanted | index($s)))
  | map(select(($scope | length) == 0 or .file == ""
               or (.file as $f | any($scope[]; . as $p | $f == $p or ($f | startswith($p + "/"))))))
  | unique
  | sort_by((.stage as $s | $order | index($s)), .file, .line)
  | {stages:$wanted, scope:$scope, count:length,
     by_stage:(group_by(.stage) | map({key:.[0].stage, value:length}) | from_entries),
     failures:.}
' "$TMP" > "${OUT}/report.json"

p_count="$(jq '.count' "${OUT}/report.json")"
if [[ "$p_count" -eq 0 ]]; then
  echo "quality gate: PASS (${STAGES})"
  exit 0
fi
echo "quality gate: FAIL — ${p_count} failure(s) $(jq -c '.by_stage' "${OUT}/report.json") -> ${OUT}/report.json"
exit 1
