#!/usr/bin/env bash
# Quality Run — the single deterministic gate shared by the agent and by Git (pre-push).
# Check-only: never formats, fixes or installs. Generated by the quality-gate skill.
#
# usage: scripts/quality/run.sh [--stage STAGE]... [--path PATH]...
#   STAGE: format | static | security | deadcode | complexity | duplication | tests | all (default)
#   PATH:  keep only failures under these paths in the report (tools still scan the repository)
set -uo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

OUT=".quality"
BASELINE="quality-baseline.json"
ALL_STAGES=(format static security deadcode complexity duplication tests)
STAGES=()
SCOPE=()

usage() {
  echo "usage: scripts/quality/run.sh [--stage ${ALL_STAGES[*]// /|}|all]... [--path PATH]..." >&2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --stage)
      IFS=',' read -r -a p_list <<< "${2:-}"
      STAGES+=("${p_list[@]}")
      shift 2
      ;;
    --path) SCOPE+=("${2:-}"); shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) usage; exit 2 ;;
  esac
done

if [[ ${#STAGES[@]} -eq 0 ]] || [[ " ${STAGES[*]} " == *" all "* ]]; then
  STAGES=("${ALL_STAGES[@]}")
fi
for p_stage in "${STAGES[@]}"; do
  if [[ " ${ALL_STAGES[*]} " != *" ${p_stage} "* ]]; then
    echo "unknown stage: ${p_stage}" >&2
    usage
    exit 2
  fi
done

if ! command -v jq >/dev/null 2>&1; then
  echo "jq not found. Run quality-gate SETUP." >&2
  exit 2
fi

baseline() {
  local p_key="$1" p_default="$2"
  if [[ -f "$BASELINE" ]]; then
    jq -r --arg d "$p_default" ".${p_key} // \$d" "$BASELINE"
  else
    echo "$p_default"
  fi
}

CYCLOMATIC_MAX="$(baseline cyclomatic_max 10)"
COGNITIVE_MAX="$(baseline cognitive_max 15)"
DUPLICATION_MAX="$(baseline duplication_max_percent 3)"

rm -rf "$OUT"
mkdir -p "$OUT"

join_by() {
  local p_sep="$1"
  shift
  local p_out="${1:-}"
  shift || true
  local p_item
  for p_item in "$@"; do p_out="${p_out}${p_sep}${p_item}"; done
  echo "$p_out"
}

EXCLUDE_DIRS=(.git .quality node_modules vendor .venv venv dist build coverage graphify-out)

# Tracked + untracked (not ignored) files matching the given extensions.
list_files() {
  local p_args=()
  local p_ext
  for p_ext in "$@"; do p_args+=("*.${p_ext}"); done
  git ls-files --cached --others --exclude-standard -- "${p_args[@]}" 2>/dev/null \
    | grep -Ev "(^|/)($(join_by '|' "${EXCLUDE_DIRS[@]}"))/" \
    | while read -r p_file; do [[ -f "$p_file" ]] && echo "$p_file"; done
}

has_python() { [[ -f pyproject.toml || -f uv.lock ]] || [[ -n "$(list_files py | head -1)" ]]; }
has_go()     { [[ -f go.mod ]] || [[ -n "$(list_files go | head -1)" ]]; }
has_js()     { [[ -f package.json ]] || [[ -n "$(list_files ts tsx js jsx mjs cjs | head -1)" ]]; }
has_php()    { [[ -f composer.json ]] || [[ -n "$(list_files php | head -1)" ]]; }

wants() { [[ " ${STAGES[*]} " == *" $1 "* ]]; }

# Normalized failure line (JSON Lines) for tools without JSON/SARIF output.
emit() {
  local p_tool="$1" p_stage="$2" p_rule="$3" p_file="$4" p_line="$5" p_msg="$6"
  jq -cn --arg tool "$p_tool" --arg stage "$p_stage" --arg rule "$p_rule" \
    --arg file "$p_file" --argjson line "${p_line:-0}" --arg message "$p_msg" \
    '{tool:$tool, stage:$stage, rule:$rule, severity:"error", file:$file, line:$line, message:$message}' \
    >> "${OUT}/${p_tool}.norm.jsonl"
}

# Records a missing tool as a failure so the gate stays red until SETUP runs.
need() {
  local p_bin="$1" p_tool="$2" p_stage="$3"
  if command -v "$p_bin" >/dev/null 2>&1; then
    return 0
  fi
  emit "$p_tool" "$p_stage" "tool-missing" "" 0 "${p_bin} not on PATH; run quality-gate SETUP"
  return 1
}

# Runs a tool; stdout+stderr go to .quality/<tool>.log, exit code to .quality/<tool>.exit.
# aggregate.sh turns a missing/invalid report into a tool-error failure.
run() {
  local p_tool="$1"
  shift
  "$@" > "${OUT}/${p_tool}.log" 2>&1
  echo "$?" > "${OUT}/${p_tool}.exit"
}

# "file:line:..." text output -> normalized lines.
emit_text() {
  local p_tool="$1" p_stage="$2" p_rule="$3" p_src="$4"
  local p_file p_line p_msg
  [[ -f "$p_src" ]] || return 0
  while IFS= read -r p_row; do
    p_file="${p_row%%:*}"
    p_line="$(echo "$p_row" | cut -d: -f2)"
    [[ "$p_line" =~ ^[0-9]+$ ]] || continue
    p_msg="$(echo "$p_row" | cut -d: -f3- | sed 's/^[0-9]*: *//; s/^ *//')"
    emit "$p_tool" "$p_stage" "$p_rule" "$p_file" "$p_line" "$p_msg"
  done < "$p_src"
}

php_paths() {
  local p_dirs=()
  local p_dir
  for p_dir in src app lib; do [[ -d "$p_dir" ]] && p_dirs+=("$p_dir"); done
  if [[ ${#p_dirs[@]} -eq 0 ]]; then
    list_files php | paste -sd, -
  else
    join_by ',' "${p_dirs[@]}"
  fi
}

GO=0; PY=0; JS=0; PHP=0
has_go && GO=1
has_python && PY=1
has_js && JS=1
has_php && PHP=1

# ---------------------------------------------------------------- format
if wants format; then
  if [[ $GO -eq 1 ]] && need gofmt gofmt format; then
    mapfile -t p_go < <(list_files go)
    if [[ ${#p_go[@]} -gt 0 ]]; then
      gofmt -l "${p_go[@]}" 2>"${OUT}/gofmt.log" | while read -r p_f; do
        emit gofmt format gofmt "$p_f" 0 "file is not gofmt-formatted"
      done
    fi
  fi
  if [[ $PY -eq 1 ]] && need ruff ruff-format format; then
    ruff format --check . 2>&1 | sed -n 's/^Would reformat: //p' | while read -r p_f; do
      emit ruff-format format ruff-format "$p_f" 0 "file is not ruff-formatted"
    done
  fi
  if [[ $JS -eq 1 ]] && need biome biome-format format; then
    run biome-format biome format --no-errors-on-unmatched --reporter=sarif --reporter-file="${OUT}/biome-format.sarif" .
  fi
  if [[ $PHP -eq 1 ]] && need php-cs-fixer php-cs-fixer format; then
    php-cs-fixer fix --dry-run --format=json --show-progress=none --config=.php-cs-fixer.dist.php \
      > "${OUT}/php-cs-fixer.json" 2> "${OUT}/php-cs-fixer.log"
    echo "$?" > "${OUT}/php-cs-fixer.exit"
  fi
fi

# ---------------------------------------------------------------- static analysis
if wants static; then
  if [[ $GO -eq 1 ]] && need staticcheck staticcheck static; then
    staticcheck -f sarif -checks "inherit,-U1000" ./... > "${OUT}/staticcheck.sarif" 2> "${OUT}/staticcheck.log"
    echo "$?" > "${OUT}/staticcheck.exit"
  fi
  if [[ $PY -eq 1 ]]; then
    if need ruff ruff-check static; then
      run ruff-check ruff check --output-format sarif --output-file "${OUT}/ruff-check.sarif" .
    fi
    if need mypy mypy static; then
      mypy --output json . > "${OUT}/mypy.jsonl" 2> "${OUT}/mypy.log"
      echo "$?" > "${OUT}/mypy.exit"
    fi
  fi
  if [[ $JS -eq 1 ]] && need biome biome-lint static; then
    run biome-lint biome lint --no-errors-on-unmatched \
      --skip=security --skip=complexity/noExcessiveCognitiveComplexity \
      --reporter=sarif --reporter-file="${OUT}/biome-lint.sarif" .
  fi
  if [[ $PHP -eq 1 ]] && need phan phan static; then
    p_ast=()
    php -m 2>/dev/null | grep -qx ast || p_ast=(--allow-polyfill-parser)
    run phan phan "${p_ast[@]}" --no-progress-bar --output-mode json --output "${OUT}/phan.json"
  fi
fi

# PHPStan runs once; aggregate.sh routes its unused-code and cognitive-complexity rules to their stages.
if [[ $PHP -eq 1 ]] && { wants static || wants deadcode || wants complexity; } && need phpstan phpstan static; then
  phpstan analyse --error-format=json --no-progress --memory-limit=1G > "${OUT}/phpstan.json" 2> "${OUT}/phpstan.log"
  echo "$?" > "${OUT}/phpstan.exit"
fi

# ---------------------------------------------------------------- security
if wants security; then
  if need gitleaks gitleaks security; then
    run gitleaks gitleaks dir . --config .gitleaks.toml --redact --no-banner --exit-code 0 \
      --report-format sarif --report-path "${OUT}/gitleaks.sarif"
  fi
  if need semgrep semgrep security; then
    mapfile -t p_configs < <(baseline 'semgrep_configs | join("\n")' "p/default")
    p_args=()
    for p_c in "${p_configs[@]}"; do p_args+=(--config "$p_c"); done
    run semgrep semgrep scan "${p_args[@]}" --metrics=off --quiet --severity WARNING --severity ERROR \
      --sarif --output "${OUT}/semgrep.sarif" .
  fi
  if [[ $GO -eq 1 ]] && need gosec gosec security; then
    run gosec gosec -quiet -severity medium -exclude-dir=vendor -fmt sarif -out "${OUT}/gosec.sarif" ./...
  fi
  if [[ $PY -eq 1 ]] && need bandit bandit security; then
    run bandit bandit -r . -ll -q -f sarif -o "${OUT}/bandit.sarif" \
      -x "./.venv,./venv,./node_modules,./vendor,./tests,./.quality"
  fi
  if [[ $JS -eq 1 ]] && need biome biome-security security; then
    run biome-security biome lint --no-errors-on-unmatched --only=security \
      --reporter=sarif --reporter-file="${OUT}/biome-security.sarif" .
  fi
fi

# ---------------------------------------------------------------- dead code
if wants deadcode; then
  if [[ $GO -eq 1 ]]; then
    if need deadcode deadcode deadcode; then
      run deadcode deadcode -test ./...
      emit_text deadcode deadcode unreachable "${OUT}/deadcode.log"
      rm -f "${OUT}/deadcode.exit"
    fi
    if need staticcheck staticcheck-u1000 deadcode; then
      staticcheck -f sarif -checks U1000 ./... > "${OUT}/staticcheck-u1000.sarif" 2> "${OUT}/staticcheck-u1000.log"
      echo "$?" > "${OUT}/staticcheck-u1000.exit"
    fi
  fi
  if [[ $PY -eq 1 ]] && need vulture vulture deadcode; then
    run vulture vulture . --min-confidence 80 --exclude ".venv,venv,node_modules,vendor,.quality"
    emit_text vulture deadcode unused "${OUT}/vulture.log"
    rm -f "${OUT}/vulture.exit"
  fi
  if [[ $JS -eq 1 && -f package.json ]] && need knip knip deadcode; then
    knip --reporter json --no-progress --no-exit-code > "${OUT}/knip.json" 2> "${OUT}/knip.log"
    echo "$?" > "${OUT}/knip.exit"
  fi
  if [[ $PHP -eq 1 ]] && need phpmd phpmd-unused deadcode; then
    run phpmd-unused phpmd "$(php_paths)" sarif unusedcode --exclude vendor --reportfile "${OUT}/phpmd-unused.sarif"
  fi
fi

# ---------------------------------------------------------------- complexity
if wants complexity; then
  if [[ $GO -eq 1 ]]; then
    mapfile -t p_go < <(list_files go)
    if [[ ${#p_go[@]} -gt 0 ]]; then
      for p_pair in "gocyclo:cyclomatic:${CYCLOMATIC_MAX}" "gocognit:cognitive:${COGNITIVE_MAX}"; do
        IFS=':' read -r p_bin p_kind p_max <<< "$p_pair"
        need "$p_bin" "$p_bin" complexity || continue
        "$p_bin" -over "$p_max" "${p_go[@]}" > "${OUT}/${p_bin}.log" 2>&1
        # "<complexity> <pkg> <func> <file>:<line>:<col>"
        while read -r p_score _ p_func p_pos; do
          [[ "$p_score" =~ ^[0-9]+$ ]] || continue
          emit "$p_bin" complexity "$p_kind" "${p_pos%%:*}" "$(echo "$p_pos" | cut -d: -f2)" \
            "${p_kind} complexity of ${p_func} is ${p_score} (max ${p_max})"
        done < "${OUT}/${p_bin}.log"
      done
    fi
  fi
  if [[ $PY -eq 1 ]]; then
    if need radon radon complexity; then
      radon cc -j -e ".venv/*,venv/*,node_modules/*,vendor/*" . > "${OUT}/radon.json" 2> "${OUT}/radon.log"
      echo "$?" > "${OUT}/radon.exit"
    fi
    if need complexipy complexipy complexity; then
      run complexipy complexipy . --max-complexity-allowed "$COGNITIVE_MAX" --failed --quiet \
        --output-format sarif --output "${OUT}/complexipy.sarif" \
        --exclude ".venv" --exclude "venv" --exclude "node_modules" --exclude "vendor"
    fi
  fi
  # Oxlint: cyclomatic (`eslint/complexity`) + cognitive (`sonarjs/cognitive-complexity`); Biome keeps format/lint/security.
  if [[ $JS -eq 1 ]] && need oxlint oxlint complexity; then
    oxlint -c .oxlintrc.json -f sarif . > "${OUT}/oxlint.sarif" 2> "${OUT}/oxlint.log"
    echo "$?" > "${OUT}/oxlint.exit"
  fi
  if [[ $PHP -eq 1 ]] && need phpmd phpmd-complexity complexity; then
    run phpmd-complexity phpmd "$(php_paths)" sarif phpmd.xml --exclude vendor --reportfile "${OUT}/phpmd-complexity.sarif"
  fi
fi

# ---------------------------------------------------------------- duplication
if wants duplication && need jscpd jscpd duplication; then
  run jscpd jscpd . --config .jscpd.json --threshold 100 --reporters json --output "${OUT}/jscpd" --silent
fi

# ---------------------------------------------------------------- tests
run_tests() {
  local p_name="$1" p_cmd="$2"
  if bash -c "$p_cmd" > "${OUT}/${p_name}.log" 2>&1; then
    return 0
  fi
  emit "$p_name" tests "tests-failed" "" 0 "\`${p_cmd}\` failed: $(tail -n 15 "${OUT}/${p_name}.log" | tr '\n' ' ' | cut -c1-1500)"
}

test_cmd() {
  local p_stack="$1" p_default="$2"
  local p_cmd
  p_cmd="$(baseline "test_commands.${p_stack}" "")"
  [[ -n "$p_cmd" ]] && { echo "$p_cmd"; return; }
  echo "$p_default"
}

if wants tests; then
  if [[ $GO -eq 1 && -f go.mod ]]; then
    run_tests tests-go "$(test_cmd go 'go test ./...')"
  fi
  if [[ $PY -eq 1 ]] && [[ -n "$(list_files py | grep -E '(^|/)(test_[^/]*|[^/]*_test)\.py$' | head -1)" ]]; then
    p_default="pytest -q"
    [[ -f uv.lock || -f pyproject.toml ]] && p_default="uv run pytest -q"
    run_tests tests-python "$(test_cmd python "$p_default")"
  fi
  if [[ $JS -eq 1 && -f package.json ]] && jq -e '.scripts.test' package.json >/dev/null 2>&1; then
    p_pm="npm"
    [[ -f pnpm-lock.yaml ]] && p_pm="pnpm"
    [[ -f yarn.lock ]] && p_pm="yarn"
    [[ -f bun.lockb || -f bun.lock ]] && p_pm="bun"
    run_tests tests-js "$(test_cmd js "${p_pm} test")"
  fi
  if [[ $PHP -eq 1 ]]; then
    p_default=""
    [[ -x vendor/bin/phpunit ]] && p_default="vendor/bin/phpunit"
    [[ -x vendor/bin/pest ]] && p_default="vendor/bin/pest"
    p_cmd="$(test_cmd php "$p_default")"
    [[ -n "$p_cmd" ]] && run_tests tests-php "$p_cmd"
  fi
fi

# ---------------------------------------------------------------- report
p_scope="$(printf '%s\n' "${SCOPE[@]+"${SCOPE[@]}"}" | jq -R . | jq -cs 'map(select(length > 0))')"
"$(dirname "${BASH_SOURCE[0]}")/aggregate.sh" \
  --stages "$(join_by ',' "${STAGES[@]}")" \
  --scope "$p_scope" \
  --cyclomatic-max "$CYCLOMATIC_MAX" \
  --cognitive-max "$COGNITIVE_MAX" \
  --duplication-max "$DUPLICATION_MAX"
