<?php

// Generated by the quality-gate skill. Unused code is covered by PHPMD + PHPStan.
// minimum_target_php_version is inferred from composer.json (require.php) when null.
$analysed = array_values(array_filter(['src', 'app', 'lib'], 'is_dir')) ?: ['.'];

return [
    'target_php_version' => null,
    'minimum_target_php_version' => null,
    'directory_list' => array_merge($analysed, is_dir('vendor') ? ['vendor'] : []),
    'exclude_analysis_directory_list' => ['vendor/', 'node_modules/', '.quality/'],
    'exclude_file_regex' => '@^(vendor|node_modules|\.quality|graphify-out)/@',
];
