<?php

// Generated by the quality-gate skill.
$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->exclude(['vendor', 'node_modules', '.quality', 'storage', 'bootstrap/cache', 'graphify-out']);

return (new PhpCsFixer\Config())
    ->setRules(['@PER-CS' => true])
    ->setFinder($finder);
